#!/bin/bash

version='0.3.0'

die() {
  printf '%s\n' "$1" >&2
  exit 1
}

show_help() {
  cat <<-EOF
Usage: doraemon [OPTIONS]

  doraemon $version, el gato cosmico.
  Collect a random item from your Pocket List.

Options:
  -b, --browser     Open item in your preferred \$BROWSER.
  -h, --help        Show this message and exit.
EOF
}

case $1 in
  -h | --help)
    show_help
    exit
    ;;
  -b | --browser)
    if ! [[ -v BROWSER ]]; then
      die 'ERROR: BROWSER environment variable not set'
    fi
    run_browser=true
    ;;
  -?*)
    die "ERROR: unknown option $1"
    ;;
  '') ;;
  *)
    die "ERROR: program takes no arguments"
    ;;
esac

if ! [[ -v POCKET_CONSUMER_KEY && -v POCKET_ACCESS_TOKEN ]]; then
  die 'ERROR: required environment variables not set'
fi

target='https://getpocket.com/v3/get'
target+="?consumer_key=$POCKET_CONSUMER_KEY"
target+="&access_token=$POCKET_ACCESS_TOKEN"

declare -a arr
readarray -t arr <<<"$(
  curl -s "$target" \
    | jq -c '.list | .[] | {id: .item_id, title: .resolved_title}' \
    | shuf -n 1 \
    | jq -r '.id, .title'
)"

item_url="https://app.getpocket.com/read/${arr[0]}"
title=${arr[1]}

if [[ "$run_browser" = true ]]; then
  "$BROWSER" "$item_url" 2>/dev/null &
elif [[ -t 1 ]]; then

  if [[ ${#title} -gt 80 ]]; then
    title="${title:0:77}..."
  fi

  tput setaf 31
  echo "$title"
  printf '%.0s-' $(seq 1 ${#title}) && echo

  tput sgr0
  echo "$item_url"
else
  echo "$item_url"
fi
