name: ci
on:
  workflow_dispatch:
  push:
    paths:
      - 'doraemon'
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run ShellCheck
        run: shellcheck doraemon
        shell: bash
